# config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_library:
  name: cloudinary
  config:
    cloud_name: hpph
    api_key: 732351866945655
    folder:
      path: 'hidinginplainsight'
media_folder: 'src/uploads'
public_folder: "/uploads"
collections:
  - name: 'cinemas'
    label: 'Cinemas'
    folder: 'src/cinemas'
    create: true
    editor:
      preview: false
    fields:
      - {label: 'Name', name: 'title', widget: 'string' }
      - {label: 'Opening date', name: 'date_open', widget: 'string', hint: 'Leave blank if unknown', required: false  }
      - {label: 'Closing date', name: 'date_close', widget: 'string', hint: 'Leave blank if unknown', required: false }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["Open", "Closed", "Demolished"]
      - label: Image
        name: image
        widget: image
        required: false'
      - {label: "Location", name: "location", widget: "map", default: '{"type":"Point","coordinates":[-1.5692493,53.8120951]}', required: false }
      - {label: 'Address or location description', name: 'address', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'text', required: false}
      - { label: 'Extended description', name: 'description_extended', widget: 'markdown', buttons: ["bold", "italic", "link"], required: false}
      - label: Photos
        name: photo
        widget: image
        required: false
        media_library:
          config:
            multiple: true